CREATE DATABASE oop;
USE oop;
CREATE TABLE user (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  dni VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(50) NOT NULL,
  country VARCHAR(50) 
) ;